"""Added hubs table and relationship

Revision ID: 82907f8783c3
Revises: 354c08ac2932
Create Date: 2026-03-16 11:09:25.878139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82907f8783c3'
down_revision = '354c08ac2932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country_members', schema=None) as batch_op:
        batch_op.alter_column('iso_a3',
               existing_type=mysql.CHAR(length=3),
               type_=sa.String(length=3),
               nullable=False)
        batch_op.create_unique_constraint(None, ['iso_a3'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('iso_a3',
               existing_type=sa.String(length=3),
               type_=mysql.CHAR(length=3),
               nullable=True)

    op.drop_table('hubs')
    # ### end Alembic commands ###
